name: xmodality_anonymed
channels:
  - https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - ld_impl_linux-64=2.44
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - pip=25.2
  - python=3.9.23
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - absl-py==2.3.1
      - array-record==0.5.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - chex==0.1.90
      - cloudpickle==3.1.1
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dm-pix==0.4.4
      - dm-tree==0.1.8
      - einops==0.8.1
      - etils==1.5.2
      - flax==0.8.5
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - grain==0.2.1
      - humanize==4.13.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jax==0.4.30
      - jax-cuda12-pjrt==0.4.30
      - jax-cuda12-plugin==0.4.30
      - jax-tqdm==0.3.1
      - jaxlib==0.4.30
      - jaxtyping==0.2.36
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - lxml==6.0.2
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.5.3
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - nest-asyncio==1.6.0
      - nibabel==5.3.2
      - nilearn==0.12.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.14.0.64
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.28.7
      - nvidia-nvjitlink-cu12==12.9.86
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.6.4
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - protobuf==6.33.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.6.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - safetensors==0.6.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.17.0
      - tensorstore==0.1.69
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - tqdm==4.67.1
      - tueplots==0.0.17
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - zipp==3.23.0
